# -*- coding: utf-8 -*-
"""Coffee_cleaning_data_processing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11RxKpQnH-Hs2LW27gWRTjGrf9FIkxmiz

# Time Series Data Preprocessing Helper Functions and Class #
"""

# Import libraries
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from statsmodels.tsa.stattools import adfuller, acf, pacf

class ItemImputer:
    '''
    Impute missing item with Random Forest Classifier using specified features (features),
    price map (price_item_map) for known item prices, and prices that are not in the map (ambiguous_prices).
    '''
    def __init__(self, features, price_item_map, ambiguous_prices):
        self.features = features
        self.price_item_map = price_item_map
        self.ambiguous_prices = ambiguous_prices
        self.model = RandomForestClassifier(
            n_estimators=300,
            random_state=42,
            class_weight="balanced"
        )

    def fit(self, df):
        # Train ONLY on ambiguous price points with known items
        train_df = df[
            df['item'].notna() &
            df['price_per_unit'].isin(self.ambiguous_prices)
        ]
        self.model.fit(train_df[self.features], train_df['item'])

    def transform(self, df):
        df = df.copy()
        df['item_imputed'] = 0
        df['imputation_confidence'] = 1.0

        # --- Apply hard rules first ---
        for price, item in self.price_item_map.items():
            mask = df['item'].isna() & (df['price_per_unit'] == price)
            df.loc[mask, 'item'] = item

        # --- ML only for ambiguous prices ---
        ambiguous_mask = (
            df['item'].isna() &
            df['price_per_unit'].isin(self.ambiguous_prices)
        )

        if ambiguous_mask.sum() > 0:
            X = df.loc[ambiguous_mask, self.features]
            probs = self.model.predict_proba(X)
            preds = self.model.classes_[probs.argmax(axis=1)]
            conf = probs.max(axis=1)

            df.loc[ambiguous_mask, 'item'] = preds
            df.loc[ambiguous_mask, 'item_imputed'] = 1
            df.loc[ambiguous_mask, 'imputation_confidence'] = conf

        return df

def aggregate_revenue(df, freq):
    '''
    Aggregate revenue data (df) based on product/item to the specified frequency (freq).
    '''

    ts = (
        df
        .groupby([pd.Grouper(key='transaction_date', freq=freq), 'item'], observed = False)
        ['total_spent']
        .sum()
        .reset_index()
        .rename(columns={
            'transaction_date': 'ds',
            'total_spent': 'y'
        })
    )
    return ts

def test_stationarity(ts, title=''):
    '''
    Perform the Augmented Dickey-Fuller test to check for stationarity and print results.
    '''

    if len(ts) < 2:
        print(f"Warning: Not enough data points for stationarity test for {title}. Series length: {len(ts)}")
        print()
        return

    result = adfuller(ts)
    print(f'ADF Test {title}:')
    print(f'ADF Statistic: {result[0]:.4f}')
    print(f'p-value: {result[1]:.4f}')
    print('Critical Values:', result[4])
    if result[1] < 0.05:
        print("-> Series is likely stationary.")
    else:
        print("-> Series is likely non-stationary.")
    print()