# -*- coding: utf-8 -*-
"""Coffee_cleaning_modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T_VkmIUF40kGcxtNbWmmdnixi0LCuUE_

# Time Series Modeling Functions #
"""

import os, re, logging
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor
from functools import partial

from ast import literal_eval

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from statsmodels.tsa.stattools import adfuller, acf, pacf
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf

from sklearn.metrics import mean_absolute_error
from statsmodels.tsa.statespace.sarimax import SARIMAX
from prophet import Prophet

def plot_acf_pacf(ts, lags = 30, title=''):
    '''
    Plot ACF and PACF for time series.
    ts: times series dataframe  with date, item, and y columns
        y column is the aggregated sales per day per item.
    lags: number of lags to plot
    title: title of plot
    '''

    fig, ax = plt.subplots(1,2, figsize=(14,4))

    # Determine max lags to avoid ValueError
    max_lags = min(lags, int(len(ts) / 2) - 1)

    if max_lags < 1:
        print(f'Warning: Not enough data points to plot ACF/PACF for {title}. Series length: {len(ts)}')
        plt.close(fig)
        return

    # ACF Subplot
    plot_acf(ts, lags=max_lags, ax=ax[0])

    # PACF Subplot
    plot_pacf(ts, lags=max_lags, ax=ax[1])

    ax[0].set_title(f'ACF {title}')
    ax[1].set_title(f'PACF {title}')

    plt.show()

def infer_d(ts):
    '''
    Infer d for time series.
    ts: times series dataframe  with date, item, and y columns
        y column is the aggregated sales per day per item.
    '''

    # Infer d based on the p-value of Augmented Dickey-Fuller Test.
    p = adfuller(ts)[1]

    return 0 if p < 0.05 else 1

def infer_p_q(ts, max_lag=14):
    '''
    Infer p and q for time series.
    ts: times series dataframe  with date, item, and y columns
        y column is the aggregated sales per day per item.
    max_lag: maximum lag to infer p and q.
    '''

    pacf_vals = pacf(ts, nlags=max_lag)
    acf_vals = acf(ts, nlags=max_lag)

    # Infer the first lag when partial autocorrelation values are less than 0.2.
    p = np.argmax(np.abs(pacf_vals[1:]) < 0.2)

    # Infer the first lag when autocorrelation values are less than 0.2.
    q = np.argmax(np.abs(acf_vals[1:]) < 0.2)

    return max(p,1), max(q,1)

def parse_tuple_string(s):
    '''
    Parse string representation (s) of tuple to actual tuple.
    '''
    s_str = str(s)

    # Replace np.int64(X) with numerical digit(s)
    s_cleaned = re.sub(r'np\.int64\((\d+)\)', r'\1', s_str)

    return literal_eval(s_cleaned)

def prepare_ts(item_group, item, freq='D', log = False):
    '''
    Prepare time series for modeling which requires
    item_group: groupby object based on item.
    item: string of item to prepare.
    freq: frequency of time series.
    log: to log transform y column (item's revenue).

    Ex. item_group = (
    daily_ts
    .sort_values('ds')
    .groupby('item', observed = False)
    )
    '''

    ts_item = (
        item_group
        .get_group(item)
        .groupby('ds', as_index = False)['y']
        .sum()
        .sort_values('ds')
        .set_index('ds')
        .asfreq(freq)
        .copy()
    )

    if log:
        ts_item['y'] = np.log1p(ts_item['y'])

    return ts_item

def add_dow_sincos_features(ts, col = 'ds'):
    '''
    Add sin/cos features for day of week to time series (ts).
    col: date column name.
    '''

    ts = ts.copy()
    ts['dow'] = ts.index.dayofweek
    ts['dow_sin'] = np.sin(2 * np.pi * ts['dow'] / 7)
    ts['dow_cos'] = np.cos(2 * np.pi * ts['dow'] / 7)

    return ts

def rolling_origin_splits(ts, initial, horizon, step):
    '''
    Split time series(ts) into rolling origin splits.
    initial: Number of initial observations in each train split.
    horizon: Number of observations in each validation split.
    step: Number of observations to move forward (window) train and validation splits.
    '''

    splits = []
    n = len(ts)

    for start in range(0, n - initial - horizon + 1, step):
        train = ts.iloc[start:start+initial]
        val = ts.iloc[start+initial:start+initial+horizon]
        splits.append((train, val))

    return splits

class TSCrossValidator:
    '''
    Time series cross-validation engine:
    - Works per item and model
    - Saves results and forecasts per fold/item to CSV
    - Resumes from existing folds

    items: list of items
    item_group: groupby object based on item.
    best_params: dictionary of best SARIMAX parameters per item.
    base_results_path: base path string to save results and forecasts.
    cv_forecast_files: CV forecast existing files to load. ('*_cv_forecasts.csv')
    cv_results_files: CV results existing files to load.('*_cv_results.csv')
    initial_train: Number of initial observations in each train split.
    horizon: Number of observations in each validation split.
    step: Number of observations to move forward (window) train and validation splits.
    model_utils: Model utility functions.
    use_exog: Boolean value on whether to use exogenous variables (dow_sin, dow_cos).
    '''

    def __init__(
        self,
        items,
        item_group,
        best_params,
        base_results_path,
        cv_forecast_files,
        cv_results_files,
        initial_train,
        horizon,
        step,
        model_utils,
        use_exog=True
    ):
        self.items = items
        self.item_group = item_group
        self.best_params = best_params
        self.base_path = base_results_path
        self.cv_forecast_files = cv_forecast_files
        self.cv_results_files = cv_results_files
        self.initial_train = initial_train
        self.horizon = horizon
        self.step = step
        self.m = model_utils
        self.use_exog = use_exog

        # In memory
        self.all_forecasts = []
        self.all_results = []

        # When reading in existing files, map data types.
        self.cv_forecast_dtypes = {
            'yhat': 'float32',
            'residual': 'float32',
            'item': 'category',
            'fold': 'int8',
            'model': 'category'
        }

        self.cv_results_dtypes = {
            'item': 'category',
            'fold': 'int8',
            'model': 'category',
            'mae': 'float32'
        }

    # Path logic
    def _get_paths(self, item, model):
        '''
        Get paths for forecasts and results.
        item: string of item.
        model: string of model.
        '''

        folder = os.path.join(self.base_path, f'item_{item}')
        os.makedirs(folder, exist_ok=True)

        # Create forecast path
        forecast_path = os.path.join(folder, f'{model}_cv_forecasts.csv')

        # Create result path
        result_path = os.path.join(folder, f'{model}_cv_results.csv')

        return forecast_path, result_path,

    # Load existing forecasts and results
    def _load_existing(self, item, model):
        '''
        Load existing forecasts and results for a given item and model.
        item: string of item.
        model: string of model.
        '''

        forecast_path, result_path = self._get_paths(item, model)

        # Read and return existing forecasts and results from CSVs.
        if os.path.exists(result_path) and os.path.exists(forecast_path):

            forecasts_df = pd.read_csv(forecast_path,
                                       dtype = self.cv_forecast_dtypes,
                                       parse_dates = ["ds"]
                                       )

            results_df = pd.read_csv(result_path,
                                     dtype = self.cv_results_dtypes)

            completed_folds = set(results_df['fold'])

            return completed_folds, forecasts_df, results_df

        return set(), pd.DataFrame(), pd.DataFrame()

    # Load all forecasts
    def load_forecasts(self):
        '''
        Load all previously saved forecasts across all items into memory.
        Returns a single combined DataFrame.
        '''

        # Searching for existing files and if not return empty Dataframe.
        base = Path(self.base_path)

        if not base.is_dir():
            return pd.DataFrame()

        files = list(base.rglob(self.cv_forecast_files))

        if not files:
            return pd.DataFrame()

        # Load data
        loader = partial(
            pd.read_csv,
            dtype = self.cv_forecast_dtypes,
            parse_dates = ['ds'],
            engine = 'pyarrow'
        )

        # Parallel processing of files
        with ThreadPoolExecutor() as executor:
            dfs = list(executor.map(loader, files))

        return pd.concat(dfs, ignore_index=True)

    # Load all results
    def load_results(self):
        '''
        Load all previously saved results across all items into memory.
        Returns a single combined DataFrame.
        '''

        # Searching for existing files and if not return empty Dataframe.
        base = Path(self.base_path)

        if not base.is_dir():
            return pd.DataFrame()

        files = list(base.rglob(self.cv_results_files))

        if not files:
            return pd.DataFrame()

        # Load data
        loader = partial(
            pd.read_csv,
            dtype = self.cv_results_dtypes,
            engine = 'pyarrow'
        )

        # Parallel processing of files
        with ThreadPoolExecutor() as executor:
            dfs = list(executor.map(loader, files))

        return pd.concat(dfs, ignore_index=True)

    # Save results and forecasts
    def _save(self, item, model, new_forecasts_df, new_results_df):
        '''
        Save forecasts and results for a given item and model.
        item: string of item.
        model: string of model.
        '''

        forecast_path, result_path = self._get_paths(item, model)

        # If file exists already, add to the existing file
        if os.path.exists(forecast_path):
            existing_forecasts = pd.read_csv(forecast_path,
                                             dtype = self.cv_forecast_dtypes,
                                             parse_dates = ['ds'])
            new_forecasts_df = pd.concat([existing_forecasts, new_forecasts_df], ignore_index=True)

        if os.path.exists(result_path):
            existing_results = pd.read_csv(result_path, dtype = self.cv_results_dtypes)
            new_results_df = pd.concat([existing_results, new_results_df], ignore_index=True)

        # Save updated files
        new_forecasts_df.to_csv(forecast_path, index=False)
        new_results_df.to_csv(result_path, index=False)

        self.all_forecasts.append(new_forecasts_df)
        self.all_results.append(new_results_df)


    # Model cross validation methods
    def _run_naive(self, train, val, item, fold):
        '''
        Run naive cross validation model.
        train: DataFrame of training data.
        val: DataFrame of validation data.
        item: string of item.
        fold: int of fold.
        '''

        # Back transform values
        val_actual = np.expm1(val['y'])
        pred = np.expm1(np.repeat(train['y'].iloc[-1], len(val)))

        # Calculate MAE
        mae = mean_absolute_error(val_actual, pred)

        # Naive Forecasts Dataframe
        forecast_df = pd.DataFrame({
            'ds': val.index,
            'yhat': pred,
            'residual': val_actual - pred,
            'item': item,
            'fold': fold,
            'model': 'naive'
        })

        # Naive Results Dataframe
        result_df = pd.DataFrame([{'item': item,
                                   'fold': fold,
                                   'model': 'naive',
                                   'mae': mae}])

        return forecast_df, result_df

    def _run_sarimax(self, train, val, params, item, fold):
        '''
        Run SARIMAX cross validation model.
        train: DataFrame of training data.
        val: DataFrame of validation data.
        params: dictionary of SARIMAX parameters.
        item: string of item.
        fold: int of fold.
        '''

        # Back transform validation y-value
        val_actual = np.expm1(val['y'])

        # Add date sine and cosine features if specified
        if self.use_exog:
            train_exog = self.m.add_dow_sincos_features(train.copy())[['dow_sin', 'dow_cos']]
            val_exog = self.m.add_dow_sincos_features(val.copy())[['dow_sin', 'dow_cos']]
        else:
            train_exog = val_exog = None

        # SARIMA(X) model and fit
        model = SARIMAX(
            train['y'],
            order=params['order'],
            seasonal_order=params['seasonal_order'],
            exog=train_exog,
            enforce_stationarity=False,
            enforce_invertibility=False
        )
        fit = model.fit(disp=False)

        # Back transform predictions
        pred = np.expm1(fit.forecast(len(val), exog=val_exog))

        # Calculate MAE
        mae = mean_absolute_error(val_actual, pred)

        # SARIMAX Forecasts Dataframe
        forecast_df = pd.DataFrame({
            'ds': val.index,
            'yhat': pred.values,
            'residual': val_actual - pred.values,
            'item': item,
            'fold': fold,
            'model': 'sarimax'
        })

        # SARIMAX Results Dataframe
        result_df = pd.DataFrame([{'item': item,
                                   'fold': fold,
                                   'model': 'sarimax',
                                   'mae': mae}])

        return forecast_df, result_df

    def _run_prophet(self, train, val, item, fold):
        '''
        Run prophet cross validation model.
        train: DataFrame of training data.
        val: DataFrame of validation data.
        item: string of item.
        fold: int of fold.
        '''

        # Back transform validation y-value
        val_actual = np.expm1(val['y'])

        # Reset and rename index
        prophet_df = (train
                      .reset_index()
                      .rename(columns={'index':'ds'}))

        # Ensure date column ('ds') is a date type.
        prophet_df['ds'] = pd.to_datetime(prophet_df['ds'])

        # Add sine and cosine exogenous variables if specified.
        if self.use_exog:
            prophet_df = self.m.add_dow_sincos_features(prophet_df.set_index('ds')).reset_index()

        # Prophet Modeling
        model = Prophet(
            weekly_seasonality=False,
            daily_seasonality=False,
            yearly_seasonality=False,
            n_changepoints=min(25, len(train))
        )

        if self.use_exog:
            model.add_regressor('dow_sin')
            model.add_regressor('dow_cos')

        model.fit(prophet_df)

        # Validation dataset preparation
        future = (val
                  .reset_index()
                  .rename(columns={'index':'ds'}))
        future['ds'] = pd.to_datetime(future['ds'])

        # Add sine and cosine exogenous variables if specified.
        if self.use_exog:
            future = self.m.add_dow_sincos_features(future.set_index('ds')).reset_index()

        # Get predictions and residuals based on validation dataset.
        forecast_full = model.predict(future)
        forecast_df = forecast_full[['ds','yhat']].copy()
        forecast_df['yhat'] = np.expm1(forecast_df['yhat'])
        forecast_df['residual'] = val_actual.values - forecast_df['yhat'].values
        forecast_df['item'] = item
        forecast_df['fold'] = fold
        forecast_df['model'] = 'prophet'

        # Calculate MAE
        mae = mean_absolute_error(val_actual, forecast_df['yhat'])

        # Prophet Forecasts Dataframe
        result_df = pd.DataFrame([{'item': item,
                                   'fold': fold,
                                   'model': 'prophet',
                                   'mae': mae}])

        return forecast_df, result_df

    # Main loop
    def run(self):
        '''
        Run cross validation for each item and model.
        '''

        for item in self.items:

            logging.info(f'Item: {item}')
            ts_item = self.m.prepare_ts(self.item_group, item, freq='D', log=True)

            if len(ts_item) < self.initial_train + self.horizon:
                logging.warning(f'Skipping {item}: insufficient data')
                continue

            # Split data
            splits = self.m.rolling_origin_splits(
                ts_item,
                self.initial_train,
                self.horizon,
                self.step
            )

            # SARIMAX best parameters dictionary
            params = self.best_params.get(item)

            # Run Naive, SARIMAX, and Prophet Cross-Validation
            for model_name in ['naive','sarimax','prophet']:

                completed_folds, forecasts_df, results_df = self._load_existing(item, model_name)
                total_folds = len(splits)

                # Skip model if done.
                if len(completed_folds) == total_folds:
                    logging.info(f'  {model_name}: all folds complete ({total_folds}), skipping.')
                    self.all_forecasts.append(forecasts_df)
                    self.all_results.append(results_df)
                    continue

                logging.info(f'Running {model_name} ({len(completed_folds)}/{total_folds} folds complete)')

                new_forecasts = []
                new_results = []

                # Continue to run models for remaining folds.
                for fold, (train, val) in enumerate(splits):

                    if fold in completed_folds:
                        logging.info(f'Fold {fold} already exists, skipping.')
                        continue

                    try:

                        if model_name == 'naive':
                            fc, res = self._run_naive(train, val, item, fold)

                        elif model_name == 'sarimax':
                            if params is None:
                                logging.warning(f'Skipping SARIMAX: no params for {item}')
                                break
                            fc, res = self._run_sarimax(train, val, params, item, fold)

                        elif model_name == 'prophet':
                            fc, res = self._run_prophet(train, val, item, fold)

                        new_forecasts.append(fc)
                        new_results.append(res)

                        logging.info(f'Fold {fold} completed.')

                    except Exception as e:
                        logging.error(f'{model_name} fold {fold} failed: {e}')

                # Save new folds
                if new_results:
                    combined_results = pd.concat(
                        [results_df] + new_results,
                        ignore_index=True
                    )

                    combined_forecasts = pd.concat(
                        [forecasts_df] + new_forecasts,
                        ignore_index=True
                    )

                    self._save(item, model_name, combined_forecasts, combined_results)

        # FINAL Forecasts and Results DataFrames.
        forecasts_df = (
            pd.concat(self.all_forecasts, ignore_index=True)
            if self.all_forecasts else pd.DataFrame()
        )

        results_df = (
            pd.concat(self.all_results, ignore_index=True)
            if self.all_results else pd.DataFrame()
        )

        return forecasts_df, results_df

class FinalForecaster:
    '''
    Generate future forecasts per item using the best model:
    - SARIMAX, Prophet, or Naive
    - Save forecasts per item
    - Load existing forecasts if present
    '''

    def __init__(self, items, item_group, summary_df, best_params, horizon, base_path, forecast_file, model_utils, use_exog=True):
        '''
        items: list of items to forecast.
        item_group: groupby object per item.
        summary_df: DataFrame of cross validation results.
        best_params: dictionary of best parameters for SARIMAX per item.
        horizon: int of forecast horizon.
        base_path: str of base path for saving forecasts.
        forecast_file: str of forecast file name.
        model_utils: ModelUtils object.
        use_exog: bool of whether to use exogenous variables.
        '''

        self.items = items
        self.item_group = item_group
        self.best_params = best_params
        self.horizon = horizon
        self.base_path = base_path
        self.forecast_file = forecast_file
        self.m = model_utils
        self.use_exog = use_exog

        self.all_forecasts = []

        # Precompute best_model map for O(1) lookup.
        self.best_model_map = dict(zip(summary_df['item'], summary_df['best_model']))

        # When reading in existing files, map out data types.
        self.final_forecast_dtypes = {
            'yhat': 'float32',
            'yhat_lower': 'float32',
            'yhat_upper': 'float32',
            'item': 'category',
            'model': 'category'
        }

    # Path logic
    def _get_path(self, item):
        '''
        Get the path for a specific item (str).
        '''
        folder = os.path.join(self.base_path, f'item_{item}')
        os.makedirs(folder, exist_ok=True)
        return os.path.join(folder, 'forecast.csv')

    # Load existing forecasts per item
    def _load_existing(self, item):
        '''
        Load existing forecasts for a specific item (str).
        '''
        path = self._get_path(item)

        if os.path.exists(path):
            return pd.read_csv(path,
                               dtype = self.final_forecast_dtypes,
                               parse_dates = ['ds'])

        return None

    # Load all forecasts
    def load_forecasts(self):
        '''
        Load all previously saved forecasts across all items into memory.
        Returns a single combined DataFrame.
        '''

        forecasts = []

        # Return an empty dataframe if the path does not exist.
        if not os.path.exists(self.base_path):
            return pd.DataFrame()

        # Joining base path with item folder
        for item_folder in os.listdir(self.base_path):
            folder_path = os.path.join(self.base_path, item_folder)

            if not os.path.isdir(folder_path):
                continue

            fc_path = os.path.join(folder_path, self.forecast_file)

            # Read existing file and append existing data into memory
            if os.path.exists(fc_path):
                try:
                    df = pd.read_csv(fc_path,
                                     dtype = self.final_forecast_dtypes,
                                     parse_dates = ['ds'])
                    forecasts.append(df)
                except Exception as e:
                    logging.error(f'Failed to load {fc_path}: {e}')

        # Forecasts dataframe
        forecasts_df = (
            pd.concat(forecasts, ignore_index=True)
            if forecasts else pd.DataFrame()
        )

        if forecasts_df.empty:
            logging.warning('No forecasts found.')

        return forecasts_df

    # Save forecast
    def _save_forecast(self, item, fc_df):
        '''
        Save forecast in run().
        item: str of item.
        fc_df: Model output as dataFrame of forecast.
        '''

        path = self._get_path(item)

        #If file exists, add new forecasts.
        if os.path.exists(path):
            existing_fc = pd.read_csv(path,
                                      dtype = self.final_forecast_dtypes,
                                      parse_dates = ['ds'])
            fc_df = pd.concat([existing_fc, fc_df], ignore_index=True)

        # Save forecast dataframe to csv.
        fc_df.to_csv(path, index=False)

        # Append forecast in memory.
        self.all_forecasts.append(fc_df)

    # Forecast methods
    def _forecast_sarimax(self, ts_item, order, seasonal_order):
        '''
        Forecast SARIMAX model
        ts_item: time series dataframe for item.
        order: tuple of order for SARIMAX model.
        seasonal_order: tuple of seasonal order for SARIMAX model.
        '''

        # Add exogenous variables if flagged
        exog = self.m.add_dow_sincos_features(ts_item)[['dow_sin','dow_cos']] if self.use_exog else None

        # SARIMAX model and fit
        model = SARIMAX(
            ts_item['y'],
            order=order,
            seasonal_order=seasonal_order,
            exog=exog,
            enforce_stationarity=False,
            enforce_invertibility=False
        )
        fit = model.fit(disp=False)

        # Create forecast dataframe
        future_dates = pd.date_range(start=ts_item.index[-1] + pd.Timedelta(days=1), periods=self.horizon, freq='D')
        future_exog = pd.DataFrame(index=future_dates)

        # Add exogenous variables to dataframe if flagged
        if self.use_exog:
            future_exog = self.m.add_dow_sincos_features(future_exog)[['dow_sin','dow_cos']]

        # Forecast SARIMAX model
        forecast_log = fit.get_forecast(steps=self.horizon, exog=future_exog)

        # Model's 95% confidence interval
        fc_df = forecast_log.conf_int(alpha=0.05)

        # Predicted mean
        fc_df['yhat'] = forecast_log.predicted_mean

        # Rename columns and reset dataframe
        fc_df = (fc_df
                 .rename(columns={'lower y':'yhat_lower','upper y':'yhat_upper'})
                 .reset_index())

        # Back transform
        fc_df[['yhat','yhat_lower','yhat_upper']] = np.expm1(fc_df[['yhat','yhat_lower','yhat_upper']])

        return fc_df

    def _forecast_prophet(self, ts_item):
        '''
        Forecast Prophet model
        ts_item: time series dataframe for item.
        '''

        # Prepare dataframe for modeling
        prophet_df = (ts_item
                      .reset_index()
                      .rename(columns={'index':'ds'})
        )
        prophet_df['ds'] = pd.to_datetime(prophet_df['ds'])

        # Add exogenous variables to dataframe if flagged
        if self.use_exog:
            prophet_df = (self.m.add_dow_sincos_features(prophet_df.set_index('ds'))
            .reset_index()
            )

        # Prophet Model
        model = Prophet(interval_width = 0.95,
                        weekly_seasonality = False,
                        yearly_seasonality = False,
                        daily_seasonality = False)

        # Add regressors if flagged
        if self.use_exog:
            model.add_regressor('dow_sin')
            model.add_regressor('dow_cos')

        # Adding seasonality
        model.add_seasonality(name='weekly', period=7, fourier_order=3)

        # Fit Prophet model
        model.fit(prophet_df)

        # Prepare forecasts dataframe
        future = model.make_future_dataframe(periods=self.horizon, freq='D')
        if self.use_exog:
            future = self.m.add_dow_sincos_features(future.set_index('ds')).reset_index()

        # Forecast model
        forecast = model.predict(future)
        fc_df = forecast[['ds','yhat','yhat_lower','yhat_upper']].iloc[-self.horizon:].copy()

        # Back transform forecasts and 95% confidence interval
        fc_df[['yhat','yhat_lower','yhat_upper']] = np.expm1(fc_df[['yhat','yhat_lower','yhat_upper']])

        return fc_df

    def _forecast_naive(self, ts_item):
        '''
        Forecast Naive model
        ts_item: time series dataframe for item.
        '''

        last_value = ts_item['y'].iloc[-1]

        # Calculate yhat with 95% confidence interval
        sigma = ts_item['y'].diff().std()
        z = 1.96
        future_dates = pd.date_range(start=ts_item.index[-1] + pd.Timedelta(days=1), periods=self.horizon, freq='D')
        mean_log = np.repeat(last_value, self.horizon)
        lower_log = mean_log - z*sigma
        upper_log = mean_log + z*sigma

        # Dataframe of forecast with 95% confidence interval
        fc_df = pd.DataFrame({
            'ds': future_dates,
            'yhat': np.expm1(mean_log),
            'yhat_lower': np.expm1(lower_log),
            'yhat_upper': np.expm1(upper_log)
        })

        return fc_df

    # Main loop
    def run(self):
        '''
        Run the best model, based on cross validation results, to forecast each item.
        '''
        for item in self.items:

            logging.info(f'Forecasting item: {item}')

            # Skip if forecast exists
            existing_fc = self._load_existing(item)
            if existing_fc is not None:
                logging.info(f'Skipping {item}: forecast already exists')
                self.all_forecasts.append(existing_fc)
                continue

            # Prepare time series
            ts_item = self.m.prepare_ts(self.item_group, item, freq='D', log=True)

            if len(ts_item) < 10:
                logging.warning(f'Skipping {item}: insufficient data ({len(ts_item)} points)')
                continue

            # Lookup best model
            best_model = self.best_model_map.get(item)

            if best_model is None:
                logging.warning(f'Skipping {item}: best_model not found')
                continue

            try:

                if best_model == 'sarimax':
                    params = self.best_params.get(item)

                    if params is None:
                        logging.warning(f'Skipping {item}: missing SARIMAX params')
                        continue

                    fc_df = self._forecast_sarimax(
                        ts_item,
                        params['order'],
                        params['seasonal_order']
                    )

                elif best_model == 'prophet':
                    fc_df = self._forecast_prophet(ts_item)

                elif best_model == 'naive':
                    fc_df = self._forecast_naive(ts_item)

                else:
                    logging.warning(f'Skipping {item}: unknown model {best_model}')
                    continue

                fc_df['item'] = item
                fc_df['model'] = best_model

                # Save forecasts
                self._save_forecast(item, fc_df)

                # Append to memory
                self.all_forecasts.append(fc_df)

                logging.info(f'Saved forecast for {item}')

            except Exception:
                logging.exception(f'Forecasting failed for {item}')

        # Final forecasts
        final_forecasts = (pd.concat(self.all_forecasts, ignore_index=True)
                           if self.all_forecasts
                           else pd.DataFrame()
                           )

        return final_forecasts

def plot_residual_diagnostics(df, item, model):
    '''
    Plot residual diagnostics for a specific item and model.
    df: DataFrame subset for a specific (item, model) group.
    '''

    if df.empty:
        print(f'No data found for item: {item}, model: {model}. Skipping residual diagnostics.')
        return

    residuals = (df[['ds', 'residual']]
                 .dropna(subset=['residual'])
    )

    if residuals.empty:
        print(f'Residuals are all NaN or empty for item: {item}, model: {model} after dropping NaNs. Skipping ACF/PACF plots.')
        return

    plt.figure(figsize=(14, 6))

    # Residuals over time
    plt.subplot(1, 2, 1)
    plt.plot(residuals['ds'], residuals['residual'], marker='o', linestyle='-', color='red')
    plt.title(f'Residuals over time - {item} - {model}')
    plt.xlabel('Date')
    plt.ylabel('Residual (Actual - Forecast)')

    # Autocorrelation of residuals
    plt.subplot(1, 2, 2)
    plot_acf(residuals['residual'], lags=30, ax=plt.gca())
    plt.title('Residuals Autocorrelation')

    plt.tight_layout()

    plt.show()

def highlight_decision(row):
    '''
    Returns a style list for a DataFrame row:
    - Promote → light green
    - Consider Removal → light red
    - Keep → no highlight
    '''
    if row['decision'] == 'Promote':
        style = 'background-color: lightgreen'
    elif row['decision'] == 'Consider Removal':
        style = 'background-color: lightcoral'  # light red
    else:
        style = ''  # Keep or other decisions, no highlight

    # Apply same style to all columns in the row
    return [style] * len(row)

def highlight_min_mae(cols, row):
    '''
    Highlights the minimum MAE value(s) in a row (among mae_cols) with light green.
    '''
    min_value = row[cols].min()

    # Build a list of styles for each column
    styles = []
    for col in row.index:
        if col in cols and row[col] == min_value:
            styles.append('background-color: lightgreen')
        else:
            styles.append('')

    return styles